spring :
  application :
    name : shorturl
    security :
      user:
        name : Emily
        password : 123
      admin:
        name : Swara
        password : 12345

  datasource:
    url : jdbc:h2:mem:shorturldb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database:
      platform: org.hibernate.dialect.H2Dialect
    show-sql: true

